spring:
  profiles: local
  application:
    name: monitor
  boot:
    admin:
      ui:
        title: KAFD Monitor
        brand: KAFT Microservices platform
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    home-page-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
#logging:
 # file: D:/log/services.log
server:
  port: 9092
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS